version: "3.8"
services:
    postgres:
        image: "postgres"
        environment:
            - POSTGRES_USER=jwa
            - POSTGRES_PASSWORD=jwalab
            - POSTGRES_DB=item
        ports:
            - "5432:5432"
