#! /usr/bin/env bash

set -euo pipefail

function build-docker-images() {
    docker run -it --rm node:16-alpine npm install
    docker run -it --rm node:16-alpine npm run build

    pushd ./packages/item-service
    ./run docker-build
    ./run docker-tag
    ./run docker-push
    popd

    pushd ./packages/tezos-work-queue
    ./run docker-build
    ./run docker-tag
    ./run docker-push
    popd
}

"$@"
