#! /usr/bin/env bash

set -euo pipefail

services="item-service tezos-gateway"

function docker-build() {
    for service in ${services[@]}
    do
        pushd packages/${service}
        ./run docker-build
        popd
    done
}

function docker-tag() {
    for service in ${services[@]}
    do
        pushd packages/${service}
        ./run docker-tag
        popd
    done
}

function docker-push() {
    for service in ${services[@]}
    do
        pushd packages/${service}
        ./run docker-push
        popd
    done
}

"$@"
